const getUser=new Promise((resolve,reject)=>{setTimeout(()=>{let error=!1;resolve({name:"John",age:30})},1e3)}).then(user=>{console.log(user.name)}).catch(error=>console.log(error)).finally(()=>{console.log("The promise has been resolved or rejected")});